### PR TITLE
Command dir in package.json is 'lib', not 'src'

### PR DESCRIPTION
**Pull request by ffissore**
Change-type: patch
Signed-off-by: Federico Fissore <federico@balena.io>

---
##### Contributor checklist
- [ ] Introduces security considerations
- [ ] Affects the development, build or deployment processes of the component

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---

### CODE REVIEW

**Comment by ffissore** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@ffissore the version badge is also pointing at a different katapult package, could you update that as well please?

**Comment by ffissore** [comment]
@balena-ci retest

**Comment by ffissore** [comment]
@balena-ci retest

**Comment by ffissore** [comment]
@balena-ci retest

**Pull request merged**
